CREATE TABLE IF NOT EXISTS Genre(
id SERIAL PRIMARY KEY,
name VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS Performers(
id SERIAL PRIMARY KEY,
name VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS Genre_Performers(
genre_id INTEGER NOT NULL REFERENCES Genre(id),
performers_id INTEGER NOT NULL REFERENCES Performers(id)
);

CREATE TABLE IF NOT EXISTS Album(
id SERIAL PRIMARY KEY,
name VARCHAR(60),
year_of_issue DATE
);

CREATE TABLE IF NOT EXISTS Performers_album(
album_id INTEGER NOT NULL REFERENCES Album(id),
performers_id INTEGER NOT NULL REFERENCES Performers(id)
);

CREATE TABLE IF NOT EXISTS Track(
id serial PRIMARY KEY,
album_id INTEGER NOT NULL REFERENCES Album(id),
name VARCHAR(60),
duration TIME
);

CREATE TABLE IF NOT EXISTS Playlist(
id serial PRIMARY KEY,
name VARCHAR(60),
year_of_issue DATE
);

CREATE TABLE IF NOT EXISTS Playlist_track(
playlist_id INTEGER NOT NULL REFERENCES Playlist(id),
track_id INTEGER NOT NULL REFERENCES Track(id)
);
